networks:
  openCodeNetwork:
    driver: bridge
services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_USER}
      POSTGRES_USER: ${DB_PASSWORD}
    ports:
      - '5433:5432'
    networks:
      - openCodeNetwork
  adminer:
    image: adminer:latest
    container_name: openCode-adminer
    restart: always
    ports:
      - "2080:8080"
    networks:
      - openCodeNetwork
  gccCompiler:
    image: gcc:14.2.0
    container_name: openCode-GccCompiler
    command: ["sh", "-c", "apt update && apt install time && tail -f /dev/null"]
    tty: true
    init: true
    networks:
      - openCodeNetwork
  python3Interpreter:
    image: python:3
    container_name: openCode-pythonInterpreter
    command: ["sh", "-c", "apt update && apt install time && tail -f /dev/null"]
    tty: true
    init: true
    networks:
      - openCodeNetwork
  app:
    image: open-code-app
    container_name: openCode-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - C:\Users\termi\IdeaProjects\openCode\.env:/app/.env
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - openCodeNetwork